#! /bin/bash

echo Creating $1 on Amazon Route53.
TLD=$(sed 's/.*\.\(.*\..*\)/\1/' <<< $1).
echo Looking up public IPv4 address from Akamai.
PUBLIC_IP=$(dig ANY +short @ns1-1.akamaitech.net whoami.akamai.net)
echo IPv4: $PUBLIC_IP
echo Creating temp JSON file for new DNS entry.
cat > tmp.dns.json << EOF
{
    "Comment": "CREATE/DELETE/UPSERT a record ",
    "Changes": [{
        "Action": "CREATE",
        "ResourceRecordSet": {
            "Name": "$1",
            "Type": "A",
            "TTL": 60,
            "ResourceRecords": [{
                "Value": "$PUBLIC_IP"
            }]
        }
    }]
}
EOF
echo Looking up Amazon Route53 hosted zone ID for $TLD
HOSTED_ZONE_ID=$(aws route53 list-hosted-zones-by-name | jq -r --arg TLD "$TLD" '.HostedZones[] | select(.Name == $TLD) | .Id' | awk -F'/' '{print $3}')
echo Host zone ID: $HOSTED_ZONE_ID
echo Submitting new DNS record to Amazon Route 53
aws route53 \
    change-resource-record-sets \
    --hosted-zone-id $HOSTED_ZONE_ID \
    --change-batch file://tmp.dns.json
echo New DNS record created.
echo Cleaning up temporary files.
rm -rf tmp.dns.json
